// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ireboirchkwtigxtgpyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZWJvaXJjaGt3dGlneHRncHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTgzNTMsImV4cCI6MjA2MzMzNDM1M30.EXqlf36o2MGcXQWG3YBPTCzvWWsQRPQiy-3Ctuvd2Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);